export interface PollState {
  visible: boolean;
  failures: number;
}

export function nextPollDelay(state: PollState): number {
  if (!state.visible) return 15_000;
  if (state.failures === 0) return 1_000;
  return Math.min(15_000, 1_000 * 2 ** (state.failures - 1));
}

export function newestSequence(current: number, rows: Array<{ sequence: number }>): number {
  return rows.reduce((newest, row) => Math.max(newest, row.sequence), current);
}

export const ADMIN_BROWSER_SOURCE = String.raw`
(() => {
  const byId = (id) => document.getElementById(id);
  const state = { projectId: null, tab: "activity", failures: 0, sequences: { activity: 0, messages: 0 }, rows: { activity: [], messages: [], agents: [] }, pendingActivity: [], agents: [], pollTimer: null, polling: false };
  const app = byId("app"); const loginForm = byId("login-form");
  const setText = (id, value) => { const node = byId(id); if (node) node.textContent = String(value); };
  const setStatus = (connected, detail) => { const node = byId("connection-status"); if (node) { node.dataset.state = connected ? "connected" : "disconnected"; node.textContent = detail || (connected ? "Connected" : "Disconnected"); } };
  const request = async (path, options) => { const response = await fetch(path, { credentials: "same-origin", ...options }); if (!response.ok) throw new Error("Request failed"); return response.status === 204 ? null : response.json(); };
  const clear = (node) => { while (node.firstChild) node.removeChild(node.firstChild); };
  const option = (value, label) => { const node = document.createElement("option"); node.value = value; node.textContent = label; return node; };
  const select = (name, label, choices) => { const wrapper = document.createElement("label"); wrapper.className = "field"; wrapper.textContent = label; const node = document.createElement("select"); node.name = name; node.append(option("", "All")); choices.forEach((choice) => node.append(option(choice.value, choice.label))); wrapper.append(node); return wrapper; };
  const badge = (value, kind) => { const node = document.createElement("span"); node.className = "badge " + kind; node.textContent = value; return node; };
  const cell = (value) => { const node = document.createElement("td"); if (typeof value === "string" || typeof value === "number") node.textContent = String(value); else node.append(value); return node; };
  const formatTime = (value) => new Date(value).toLocaleString();
  const query = (extra) => { const params = new URLSearchParams(); const filters = byId("filters"); if (filters) filters.querySelectorAll("select").forEach((field) => { if (field.value) params.set(field.name, field.value); }); Object.entries(extra || {}).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== "") params.set(key, String(value)); }); const text = params.toString(); return text ? "?" + text : ""; };
  const renderSummary = (summary) => { setText("summary-project", summary.project.name); setText("summary-agents", summary.agents.online + " / " + summary.agents.total); setText("summary-messages", summary.messages.unacknowledged + " / " + summary.messages.total); setText("summary-failures", summary.failures_last_24h); };
  const renderFilters = () => { const filters = byId("filters"); clear(filters); if (state.tab === "agents") { filters.hidden = true; return; } filters.hidden = false; const agents = state.agents.map((agent) => ({ value: agent.id, label: agent.name })); filters.append(select("agent_id", "Agent", agents)); if (state.tab === "activity") { filters.append(select("event_type", "Event type", ["agent.registered", "agent.registration_failed", "agent.synced", "message.sent", "message.send_failed", "message.acknowledged", "mcp.request_failed"].map((value) => ({ value, label: value })))); filters.append(select("outcome", "Outcome", [{ value: "success", label: "Success" }, { value: "failure", label: "Failure" }])); } if (state.tab === "messages") filters.append(select("acknowledged", "Acknowledged", [{ value: "true", label: "Acknowledged" }, { value: "false", label: "Unacknowledged" }])); filters.querySelectorAll("select").forEach((field) => field.addEventListener("change", () => { state.sequences[state.tab] = 0; loadActive().catch(disconnected); })); };
  const header = (labels) => { const row = document.createElement("tr"); labels.forEach((label) => { const item = document.createElement("th"); item.scope = "col"; item.textContent = label; row.append(item); }); return row; };
  const renderRows = () => { const dataView = byId("data-view"); clear(dataView); const rows = state.rows[state.tab]; if (rows.length === 0) { const empty = document.createElement("p"); empty.className = "empty"; empty.textContent = "No matching records"; dataView.append(empty); return; } const table = document.createElement("table"); const head = document.createElement("thead"); const body = document.createElement("tbody"); if (state.tab === "activity") { head.append(header(["Event", "Outcome", "Actor", "When"])); rows.forEach((item) => { const row = document.createElement("tr"); row.append(cell(item.event_type), cell(badge(item.outcome, item.outcome)), cell(item.actor ? item.actor.name : "System"), cell(formatTime(item.created_at))); body.append(row); }); } if (state.tab === "messages") { head.append(header(["From", "To", "Preview", "Acknowledgement", "When"])); rows.forEach((item) => { const row = document.createElement("tr"); const open = document.createElement("button"); open.type = "button"; open.className = "row-button"; open.textContent = item.preview; open.addEventListener("click", () => openMessage(item.id)); row.append(cell(item.sender.name), cell(item.recipient.name), cell(open), cell(badge(item.acknowledged_at ? "Acknowledged" : "Unacknowledged", item.acknowledged_at ? "success" : "failure")), cell(formatTime(item.created_at))); body.append(row); }); } if (state.tab === "agents") { head.append(header(["Agent", "Client", "Presence", "Last seen"])); rows.forEach((item) => { const row = document.createElement("tr"); row.append(cell(item.name), cell(item.client), cell(badge(item.status, item.status)), cell(formatTime(item.last_seen_at))); body.append(row); }); } table.append(head, body); dataView.append(table); };
  const applyAcknowledgements = (events) => { events.filter((event) => event.event_type === "message.acknowledged" && event.message_id).forEach((event) => { state.rows.messages.forEach((message) => { if (message.id === event.message_id) message.acknowledged_at = event.created_at; }); }); if (state.tab === "messages") renderRows(); };
  const disconnected = () => { state.failures += 1; setStatus(false, "Disconnected"); };
  const openMessage = async (messageId) => { try { const item = await request("/api/admin/projects/" + encodeURIComponent(state.projectId) + "/messages/" + encodeURIComponent(messageId)); setText("drawer-title", "Message details"); setText("drawer-text", item.text); byId("detail-drawer").hidden = false; byId("drawer-close").focus(); } catch { disconnected(); } };
  const updateRows = (tab, rows, replace) => { if (tab === "activity" && !replace && window.scrollY > 80) { state.pendingActivity = rows.concat(state.pendingActivity); byId("new-activity").hidden = false; return; } state.rows[tab] = replace ? rows : rows.concat(state.rows[tab]); if (tab === state.tab) renderRows(); };
  const endpointForTab = () => state.tab === "activity" ? "events" : state.tab;
  const loadActive = async () => { if (!state.projectId) return; const result = await request("/api/admin/projects/" + encodeURIComponent(state.projectId) + "/" + endpointForTab() + query()); updateRows(state.tab, result.items, true); if (state.tab === "activity" || state.tab === "messages") state.sequences[state.tab] = result.items.reduce((newest, item) => Math.max(newest, item.sequence), 0); };
  const loadProject = async () => { if (!state.projectId) return; const base = "/api/admin/projects/" + encodeURIComponent(state.projectId); const [summary, agents] = await Promise.all([request(base + "/summary"), request(base + "/agents")]); renderSummary(summary); state.agents = agents.items; state.rows = { activity: [], messages: [], agents: [] }; state.sequences = { activity: 0, messages: 0 }; renderFilters(); await loadActive(); };
  const loadProjects = async () => { const projects = await request("/api/admin/projects"); const selector = byId("project-selector"); clear(selector); projects.items.forEach((project) => selector.append(option(project.id, project.name))); if (!state.projectId) state.projectId = projects.items[0] ? projects.items[0].id : null; if (state.projectId) selector.value = state.projectId; await loadProject(); };
  const schedulePoll = (delay) => { if (state.pollTimer !== null) window.clearTimeout(state.pollTimer); state.pollTimer = window.setTimeout(poll, delay); };
  const poll = async () => { if (state.polling) return; state.polling = true; try { if (state.projectId && (state.tab === "activity" || state.tab === "messages")) { const tab = state.tab; let after = state.sequences[tab]; let newest = after; let hasMore = true; const received = []; while (hasMore) { const result = await request("/api/admin/projects/" + encodeURIComponent(state.projectId) + "/" + endpointForTab() + query({ after })); received.push(...result.items); newest = result.items.reduce((latest, item) => Math.max(latest, item.sequence), newest); hasMore = result.has_more === true; after = newest; } if (received.length > 0) { if (tab === "activity") applyAcknowledgements(received); updateRows(tab, received, false); } state.sequences[tab] = newest; } state.failures = 0; setStatus(true, "Connected"); } catch { disconnected(); } finally { state.polling = false; schedulePoll(document.hidden ? 15000 : (state.failures === 0 ? 1000 : Math.min(15000, 1000 * 2 ** (state.failures - 1)))); } };
  const boot = async () => { try { await loadProjects(); setStatus(true, "Connected"); } catch { disconnected(); } poll(); };
  if (loginForm) loginForm.addEventListener("submit", async (event) => { event.preventDefault(); const error = byId("login-error"); error.textContent = ""; try { const response = await fetch("/admin/session", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: byId("login-token").value }) }); if (!response.ok) throw new Error("Login failed"); window.location.reload(); } catch { error.textContent = "Sign in failed. Check the token and try again."; } });
  if (app) { byId("project-selector").addEventListener("change", (event) => { state.projectId = event.currentTarget.value; loadProject().catch(disconnected); }); document.querySelectorAll("[role=tab]").forEach((tab) => tab.addEventListener("click", () => { state.tab = tab.dataset.tab; document.querySelectorAll("[role=tab]").forEach((item) => item.setAttribute("aria-selected", String(item === tab))); renderFilters(); loadActive().catch(disconnected); })); byId("logout-button").addEventListener("click", async () => { await fetch("/admin/session", { method: "DELETE", credentials: "same-origin" }); window.location.reload(); }); byId("drawer-close").addEventListener("click", () => { byId("detail-drawer").hidden = true; }); byId("new-activity").addEventListener("click", () => { state.rows.activity = state.pendingActivity.concat(state.rows.activity); state.pendingActivity = []; byId("new-activity").hidden = true; renderRows(); window.scrollTo({ top: 0, behavior: "smooth" }); }); document.addEventListener("visibilitychange", () => { schedulePoll(document.hidden ? 15000 : 0); }); boot(); }
})();
`;
